// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNEZgBZIan2l89PUGmrY6Y_c10KoUI-PM',
    appId: '1:1079984537155:web:a9b2805c986e4671e39ef6',
    messagingSenderId: '1079984537155',
    projectId: 'inclass17',
    authDomain: 'inclass17.firebaseapp.com',
    storageBucket: 'inclass17.firebasestorage.app',
    measurementId: 'G-QVJN5DV05Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5V9Hcy5RlUh6GXJsq9SJ_RYqUKQsZjk',
    appId: '1:1079984537155:android:cb0bb51f9efe4b84e39ef6',
    messagingSenderId: '1079984537155',
    projectId: 'inclass17',
    storageBucket: 'inclass17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApDljf3WTHtig-KoPoDsxOQWvIo1yBKnw',
    appId: '1:1079984537155:ios:55a62c6accad87cae39ef6',
    messagingSenderId: '1079984537155',
    projectId: 'inclass17',
    storageBucket: 'inclass17.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApDljf3WTHtig-KoPoDsxOQWvIo1yBKnw',
    appId: '1:1079984537155:ios:55a62c6accad87cae39ef6',
    messagingSenderId: '1079984537155',
    projectId: 'inclass17',
    storageBucket: 'inclass17.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNEZgBZIan2l89PUGmrY6Y_c10KoUI-PM',
    appId: '1:1079984537155:web:f9069e1bcdf7ac39e39ef6',
    messagingSenderId: '1079984537155',
    projectId: 'inclass17',
    authDomain: 'inclass17.firebaseapp.com',
    storageBucket: 'inclass17.firebasestorage.app',
    measurementId: 'G-RRL2Y08GQG',
  );
}
